import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { corsHeaders, handleCORS } from '../_shared/cors.ts'

// Function to generate random code
function generateCode(length = 6) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}

async function handler(req: Request): Promise<Response> {
    const corsResponse = handleCORS(req)
    if (corsResponse) return corsResponse

    try {
        const supabaseClient = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_ANON_KEY') ?? '',
            { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
        )

        const { data: { user }, error: authError } = await supabaseClient.auth.getUser()
        if (authError || !user) throw new Error('Unauthorized')

        if (req.method === 'GET') {
            const url = new URL(req.url)
            const roomId = url.searchParams.get('room_id')

            if (!roomId) {
                return new Response(JSON.stringify({ error: 'room_id is required' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
            }

            // Fetch valid active code
            const { data, error } = await supabaseClient
                .from('flat_invitation_codes')
                .select('*')
                .eq('room_id', roomId)
                .eq('created_by', user.id)
                .eq('is_active', true)
                .gt('expires_at', new Date().toISOString())
                .order('created_at', { ascending: false })
                .limit(1)
                .maybeSingle()

            if (error) throw error;

            return new Response(JSON.stringify({ data }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
        }

        if (req.method === 'POST') {
            const body = await req.json()
            const { room_id, max_uses = 1 } = body

            if (!room_id) {
                return new Response(JSON.stringify({ error: 'room_id is required' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
            }

            // Verify ownership
            const { data: room, error: roomError } = await supabaseClient
                .from('rooms')
                .select('owner_id')
                .eq('id', room_id)
                .single()

            if (roomError || !room || room.owner_id !== user.id) {
                return new Response(JSON.stringify({ error: 'Unauthorized to generate code for this room' }), { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
            }

            const adminClient = createClient(
                Deno.env.get('SUPABASE_URL') ?? '',
                Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
            );

            // Invalidate previous active codes for this room generated by this user
            await adminClient
                .from('flat_invitation_codes')
                .update({ is_active: false })
                .eq('room_id', room_id)
                .eq('created_by', user.id)
                .eq('is_active', true);

            // Generate a unique code
            let code = '';
            let isUnique = false;

            for (let i = 0; i < 3; i++) {
                code = generateCode();
                const { data: existing } = await adminClient.from('flat_invitation_codes').select('id').eq('code', code).maybeSingle();
                if (!existing) {
                    isUnique = true;
                    break;
                }
            }

            if (!isUnique) throw new Error('Failed to generate unique code');

            const expiresAt = new Date();
            expiresAt.setDate(expiresAt.getDate() + 7); // Valid for 7 days

            const { data, error } = await adminClient
                .from('flat_invitation_codes')
                .insert({
                    room_id,
                    created_by: user.id,
                    code,
                    max_uses,
                    expires_at: expiresAt.toISOString()
                })
                .select()
                .single()

            if (error) throw error;

            return new Response(JSON.stringify({ data }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
        }

        return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers: corsHeaders })
    } catch (error: any) {
        return new Response(JSON.stringify({ error: error.message }), { status: 500, headers: corsHeaders })
    }
}

Deno.serve(handler)
