import { StyleSheet } from 'react-native';
import type { Theme } from '../../theme';
import { getCommonStyles } from '../common';

export const createChatScreenStyles = (theme: Theme) => {
  const commonStyles = getCommonStyles(theme);
  return StyleSheet.create({
    container: commonStyles.screenContainer,
    header: {
      paddingHorizontal: 24,
      paddingVertical: 16,
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBgStrong,
    },
    headerProfile: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
    },
    headerAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
    },
    headerName: {
      fontSize: 16,
      fontWeight: '600',
    },
    headerSpacer: {
      width: 22,
    },
    assignmentPanel: {
      marginHorizontal: 16,
      marginTop: 8,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 16,
      backgroundColor: theme.colors.glassBgStrong,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      shadowColor: theme.colors.glassShadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 2,
      gap: 10,
    },
    assignmentHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    assignmentTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.text,
    },
    assignmentSubtitle: {
      marginTop: 4,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    assignmentStatusPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: theme.colors.warningLight,
    },
    assignmentStatusText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.warning,
    },
    assignActions: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
      marginTop: 6,
    },
    assignButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: theme.colors.primary,
    },
    assignButtonDisabled: {
      backgroundColor: theme.colors.disabled,
    },
    assignButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.background,
    },
    offerCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 12,
      backgroundColor: theme.colors.surface,
    },
    offerTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.text,
    },
    offerSubtitle: {
      marginTop: 6,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    offerActions: {
      marginTop: 10,
      flexDirection: 'row',
      gap: 10,
    },
    offerButton: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 999,
      alignItems: 'center',
    },
    offerAccept: {
      backgroundColor: theme.colors.primary,
    },
    offerReject: {
      backgroundColor: theme.colors.errorLight,
    },
    offerButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.background,
    },
    offerRejectText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.error,
    },
    roommatesPanel: {
      marginHorizontal: 16,
      marginTop: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 16,
      backgroundColor: theme.colors.glassBgStrong,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      shadowColor: theme.colors.glassShadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 2,
    },
    roommatesHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    roommatesTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.text,
    },
    roommatesBadge: {
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.colors.borderLight,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
    },
    roommatesBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    roommatesEmpty: {
      marginTop: 8,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    roommatesList: {
      marginTop: 10,
      gap: 6,
    },
    roommateRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    roommateName: {
      fontSize: 12,
      color: theme.colors.text,
      fontWeight: '600',
    },
    roommateRoom: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    messagesList: {
      paddingHorizontal: 16,
      paddingTop: 14,
      gap: 12,
    },
    messagesListContainer: {
      flex: 1,
    },
    daySeparator: {
      alignItems: 'center',
      marginVertical: 4,
    },
    daySeparatorText: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      backgroundColor: theme.colors.glassBgStrong,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      overflow: 'hidden',
      paddingHorizontal: 12,
      paddingVertical: 6,
      textTransform: 'capitalize',
    },
    messageRow: {
      flexDirection: 'row',
    },
    messageRowMine: {
      justifyContent: 'flex-end',
    },
    messageRowOther: {
      justifyContent: 'flex-start',
    },
    bubble: {
      maxWidth: '78%',
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 18,
      borderWidth: 1,
    },
    bubbleMine: {
      backgroundColor: 'rgba(45, 108, 223, 0.18)',
      borderColor: 'rgba(45, 108, 223, 0.25)',
      borderTopRightRadius: 4,
    },
    bubbleOther: {
      backgroundColor: theme.colors.glassBgStrong,
      borderColor: theme.colors.glassBorder,
      borderTopLeftRadius: 4,
    },
    bubbleText: {
      fontSize: 14,
      lineHeight: 20,
      color: theme.colors.text,
    },
    bubbleMeta: {
      marginTop: 6,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    bubbleTime: {
      fontSize: 10,
      color: theme.colors.textSecondary,
    },
    bubbleStatus: {
      fontSize: 10,
      color: theme.colors.primary,
      fontWeight: '600',
    },
    newMessagesButton: {
      position: 'absolute',
      alignSelf: 'center',
      bottom: 84,
      backgroundColor: theme.colors.primary,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 9,
      zIndex: 3,
      shadowColor: theme.colors.primaryDark,
      shadowOpacity: 0.24,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 3,
    },
    newMessagesText: {
      color: theme.colors.background,
      fontSize: 12,
      fontWeight: '700',
    },
    inputContainer: {
      borderTopWidth: 1,
      borderTopColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBgStrong,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 12,
      gap: 10,
    },
    input: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      fontSize: 14,
      color: theme.colors.text,
    },
    sendButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: theme.colors.overlay,
    },
    modalContent: {
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      maxHeight: '70%',
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text,
    },
    modalSubtitle: {
      marginTop: 6,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    modalList: {
      marginTop: 12,
    },
    modalRoomItem: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 10,
    },
    modalRoomItemActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.borderLight,
    },
    modalRoomTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.text,
    },
    modalRoomTitleActive: {
      color: theme.colors.primary,
    },
    modalRoomMeta: {
      marginTop: 4,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 12,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 999,
      alignItems: 'center',
    },
    modalCancel: {
      backgroundColor: theme.colors.surfaceLight,
    },
    modalCancelText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.text,
    },
    modalConfirmText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.background,
    },
    modalConfirm: {
      backgroundColor: theme.colors.primary,
    },
    modalButtonDisabled: {
      backgroundColor: theme.colors.disabled,
    },
  });
};
