import { StyleSheet } from 'react-native';
import type { Theme } from '../../theme';
import { getCommonStyles } from '../common';
import { radius, spacing } from '../tokens';

export const createRoomDetailStyles = (theme: Theme) => {
  const commonStyles = getCommonStyles(theme);
  return StyleSheet.create({
    container: commonStyles.screenContainer,
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBgStrong,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: {
      width: 22,
    },
    content: {
      flex: 1,
      paddingHorizontal: spacing.lgd,
      paddingTop: spacing.lgd,
    },
    contentContainer: {
      paddingBottom: 120,
    },
    carouselContainer: {
      marginBottom: spacing.lg,
      borderRadius: radius.xl,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.glassBgStrong,
    },
    carouselImage: {
      width: '100%',
      height: 320,
      backgroundColor: theme.colors.surfaceLight,
    },
    carouselEmptyState: {
      height: 320,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      backgroundColor: theme.colors.surfaceLight,
    },
    carouselEmptyText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    heroInfo: {
      position: 'absolute',
      left: spacing.md,
      right: spacing.md,
      bottom: spacing.md,
      borderRadius: radius.lg,
      overflow: 'hidden',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.smd,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.4)',
      backgroundColor: theme.colors.darkOverlay,
    },
    heroTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    heroMetaRow: {
      marginTop: spacing.sm,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    heroMetaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: radius.full,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.5)',
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
    },
    heroMetaText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    carouselDots: {
      position: 'absolute',
      right: spacing.md,
      top: spacing.md,
      flexDirection: 'row',
      gap: 6,
    },
    carouselDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
    },
    carouselDotActive: {
      width: 18,
      backgroundColor: '#FFFFFF',
    },
    section: {
      marginBottom: spacing.lg,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.text,
      marginBottom: spacing.sm,
    },
    detailCard: {
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: spacing.md,
      gap: spacing.smd,
      backgroundColor: theme.colors.glassBgStrong,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.smd,
    },
    detailLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexShrink: 1,
    },
    detailLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },
    detailValue: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.text,
      textAlign: 'right',
      flexShrink: 1,
    },
    pricePill: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: radius.full,
      backgroundColor: 'rgba(79, 70, 229, 0.14)',
      borderWidth: 1,
      borderColor: 'rgba(79, 70, 229, 0.24)',
    },
    pricePillText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#4338CA',
    },
    statusPill: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: radius.full,
      borderWidth: 1,
    },
    statusPillAvailable: {
      backgroundColor: 'rgba(16, 185, 129, 0.16)',
      borderColor: 'rgba(5, 150, 105, 0.26)',
    },
    statusPillOccupied: {
      backgroundColor: 'rgba(239, 68, 68, 0.14)',
      borderColor: 'rgba(220, 38, 38, 0.22)',
    },
    statusPillText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.text,
    },
    detailNote: {
      padding: spacing.smd,
      borderRadius: radius.md,
      backgroundColor: theme.colors.surfaceLight,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    detailNoteText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      lineHeight: 20,
    },
    roommateList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    roommateItem: {
      width: '48%',
      minHeight: 62,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceLight,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    roommateAvatar: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.surface,
    },
    roommateFallback: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    roommateName: {
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.text,
    },
    bottomCtaContainer: {
      position: 'absolute',
      left: spacing.md,
      right: spacing.md,
      bottom: spacing.md,
    },
    bottomCtaButton: {
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.primaryLight,
      backgroundColor: theme.colors.glassBgStrong,
    },
    bottomCtaText: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.text,
    },
  });
};
