// src/screens/RoomManagementScreen.styles.ts
import { StyleSheet } from 'react-native';
import { Theme } from '../theme';

export const makeStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.systemBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: theme.colors.glassPanel,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  headerAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  headerSpacer: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  flatSelector: {
    marginBottom: 8,
  },
  flatSelectorLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  flatChips: {
    flexDirection: 'row',
    gap: 10,
  },
  flatChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    backgroundColor: theme.colors.glassBackground,
  },
  flatChipActive: {
    borderColor: theme.colors.primary,
    backgroundColor: 'rgba(124, 58, 237, 0.10)',
  },
  flatChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  flatChipTextActive: {
    color: theme.colors.primary,
  },
  flatChipAdd: {
    borderStyle: 'dashed',
    borderColor: theme.colors.primaryLight,
    backgroundColor: 'rgba(245, 243, 255, 0.80)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  flatChipAddText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  createFlatCard: {
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 40,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    backgroundColor: theme.colors.glassBackground,
  },
  createFlatButton: {
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: theme.colors.primary,
  },
  createFlatButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  emptyStateInline: {
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  emptyTitle: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    textAlign: 'center',
  },
  emptySubtitle: {
    marginTop: 8,
    fontSize: 13,
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  detailText: {
    fontSize: 14,
    color: theme.colors.text,
  },
  detailMeta: {
    marginTop: 6,
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  detailEmpty: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  rulesList: {
    gap: 6,
  },
  servicesList: {
    gap: 8,
  },
  serviceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inlineAction: {
    marginTop: 12,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(124, 58, 237, 0.10)',
  },
  inlineActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  expenseButtonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  expenseButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(124, 58, 237, 0.10)',
  },
  sectionHint: {
    marginTop: 8,
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 10,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    backgroundColor: theme.colors.glassBackground,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  segmentButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  segmentButtonDisabled: {
    backgroundColor: theme.colors.surfaceLight,
    borderColor: theme.colors.border,
  },
  segmentButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  segmentButtonTextActive: {
    color: '#FFFFFF',
  },
  segmentButtonTextDisabled: {
    color: theme.colors.textTertiary,
  },
  roomCard: {
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    backgroundColor: theme.colors.glassBackground,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  roomCardHeader: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  roomPhoto: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceLight,
  },
  roomPhotoPlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roomInfo: {
    flex: 1,
  },
  roomTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.text,
  },
  roomMeta: {
    marginTop: 4,
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  content: {
    padding: 20,
    gap: 16,
  },
  card: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    backgroundColor: theme.colors.glassBackground,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  cardHeader: {
    marginBottom: 12,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    flex: 1,
  },
  cardMeta: {
    marginTop: 4,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    minWidth: 86,
    alignItems: 'center',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text,
  },
  statusAvailable: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
  },
  statusPaused: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
  },
  statusReserved: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
    marginTop: 12,
  },
  actionButton: {
    flexGrow: 1,
    flexBasis: '48%',
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: theme.colors.glassBackground,
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  actionText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.text,
  },
  deleteButton: {
    borderColor: 'rgba(239, 68, 68, 0.30)',
    backgroundColor: 'rgba(254, 242, 242, 0.80)',
  },
  deleteButtonText: {
    color: theme.colors.error,
  },
  // Invitation code modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  codeModal: {
    width: '100%',
    borderRadius: 20,
    padding: 24,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.glassBorder,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  codeModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: 4,
  },
  codeModalRoom: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 20,
  },
  codeBox: {
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 32,
    backgroundColor: 'rgba(124, 58, 237, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.20)',
    marginBottom: 10,
  },
  codeText: {
    fontSize: 32,
    fontWeight: '800',
    color: theme.colors.primary,
    letterSpacing: 6,
    fontVariant: ['tabular-nums'],
  },
  codeExpiry: {
    fontSize: 12,
    color: theme.colors.textTertiary,
    marginBottom: 20,
  },
  codeActions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  codeActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(124, 58, 237, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.20)',
  },
  codeActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  codeCloseButton: {
    paddingVertical: 8,
    paddingHorizontal: 24,
  },
  codeCloseText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
});
