import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../tokens';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#EEF1F6',
  },
  container: {
    flex: 1,
    backgroundColor: '#EEF1F6',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.45)',
    backgroundColor: 'rgba(255, 255, 255, 0.66)',
  },
  headerSpacer: {
    width: 48,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.glassBgStrong,
    borderWidth: 1,
    borderColor: colors.glassBorder,
  },
  headerIconDanger: {
    backgroundColor: 'rgba(254, 226, 226, 0.78)',
    borderColor: 'rgba(248, 113, 113, 0.45)',
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  contentContainer: {
    paddingBottom: spacing.lg,
  },
  contentContainerWithActions: {
    paddingBottom: 118,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: spacing.smd,
    marginBottom: spacing.lgd,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    alignItems: 'center',
    backgroundColor: colors.glassBgStrong,
  },
  tabButtonActive: {
    borderColor: 'rgba(124, 58, 237, 0.32)',
    backgroundColor: 'rgba(124, 58, 237, 0.14)',
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#596074',
  },
  tabTextActive: {
    color: colors.primaryDark,
  },
  heroCard: {
    borderRadius: radius.xl,
    overflow: 'hidden',
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.glassBg,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 6,
  },
  heroImage: {
    width: '100%',
    height: 420,
    backgroundColor: '#D8DEE8',
  },
  heroImagePlaceholder: {
    width: '100%',
    height: 360,
    backgroundColor: '#D8DEE8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroOverlay: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.smd,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.darkOverlay,
  },
  heroName: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  heroMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  heroMetaChipText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  heroDots: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.md,
    flexDirection: 'row',
    gap: 6,
  },
  heroDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
  },
  heroDotActive: {
    backgroundColor: '#FFFFFF',
    width: 18,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.smd,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  sectionMutedTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#566074',
    marginBottom: spacing.sm,
  },
  detailCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    padding: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    shadowColor: colors.glassShadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 3,
  },
  aboutText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#344054',
  },
  compactChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  compactChip: {
    maxWidth: '100%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.58)',
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
  },
  compactChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#213047',
    flexShrink: 1,
  },
  mutedText: {
    fontSize: 13,
    color: '#667085',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailRowSpacing: {
    marginTop: spacing.md,
  },
  detailIcon: {
    width: 42,
    height: 42,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.smd,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
  },
  detailIconBlue: {
    backgroundColor: 'rgba(37, 99, 235, 0.16)',
  },
  detailIconGreen: {
    backgroundColor: 'rgba(5, 150, 105, 0.16)',
  },
  detailIconPurple: {
    backgroundColor: 'rgba(124, 58, 237, 0.16)',
  },
  detailText: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#667085',
    letterSpacing: 0.4,
  },
  detailValue: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: '700',
    color: '#172235',
  },
  housingRow: {
    gap: spacing.sm,
  },
  housingBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'rgba(124, 58, 237, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.34)',
  },
  housingBadgeText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '700',
  },
  housingDescription: {
    color: '#344054',
    fontSize: 14,
    lineHeight: 21,
  },
  flatCtaButton: {
    marginTop: spacing.smd,
    alignSelf: 'flex-start',
    borderRadius: radius.full,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: 'rgba(17, 24, 39, 0.9)',
  },
  flatCtaButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  manageCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    padding: spacing.md,
  },
  manageInfo: {
    marginBottom: spacing.smd,
  },
  manageTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#172235',
  },
  manageSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 19,
    color: '#667085',
  },
  manageButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
  },
  manageButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  flatList: {
    gap: spacing.md,
  },
  flatCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    padding: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.76)',
  },
  flatTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#172235',
  },
  flatMeta: {
    marginTop: 6,
    fontSize: 12,
    color: '#596074',
  },
  flatSection: {
    marginTop: spacing.md,
  },
  flatSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1C2A40',
    marginBottom: spacing.sm,
  },
  listContainer: {
    gap: 6,
  },
  listItem: {
    fontSize: 12,
    color: '#374151',
    lineHeight: 17,
  },
  roomList: {
    gap: spacing.sm,
  },
  roomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.smd,
    padding: spacing.smd,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.66)',
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
  },
  roomPhoto: {
    width: 68,
    aspectRatio: 1,
    borderRadius: radius.md,
    backgroundColor: '#E3E8F0',
  },
  roomPhotoPlaceholder: {
    width: 68,
    aspectRatio: 1,
    borderRadius: radius.md,
    backgroundColor: '#E3E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roomInfo: {
    flex: 1,
  },
  roomTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#172235',
  },
  roomMeta: {
    marginTop: 3,
    fontSize: 12,
    color: '#596074',
  },
  bottomActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.lgd,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.46)',
    backgroundColor: 'rgba(238, 241, 246, 0.92)',
  },
  bottomButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: colors.glassBgStrong,
    borderColor: colors.glassBorder,
    overflow: 'hidden',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 5,
  },
  rejectButton: {
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  likeButton: {
    borderColor: 'rgba(124, 58, 237, 0.4)',
  },
  glassTint: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
  },
  rejectTint: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
  },
  likeTint: {
    backgroundColor: 'rgba(124, 58, 237, 0.1)',
  },
  lightboxOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightboxBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  lightboxContent: {
    width: '90%',
    height: '70%',
    borderRadius: radius.xl,
    overflow: 'hidden',
  },
  lightboxImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    backgroundColor: '#000000',
  },
  lightboxClose: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(17, 24, 39, 0.82)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
