import { StyleSheet } from 'react-native';
import { commonStyles } from '../common';
import { colors, radius, spacing } from '../tokens';

const styles = StyleSheet.create({
  container: commonStyles.screenContainer,
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.45)',
    backgroundColor: 'rgba(255, 255, 255, 0.66)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  headerSpacer: {
    width: 22,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.lgd,
    paddingTop: spacing.lgd,
  },
  contentContainer: {
    paddingBottom: 120,
  },
  carouselContainer: {
    marginBottom: spacing.lg,
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.glassBg,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 6,
  },
  carouselImage: {
    width: '100%',
    height: 320,
    backgroundColor: '#D8DEE8',
  },
  carouselEmptyState: {
    height: 320,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: '#DCE3EE',
  },
  carouselEmptyText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#556177',
  },
  heroInfo: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    borderRadius: radius.lg,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.smd,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.darkOverlay,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  heroMetaRow: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  heroMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  heroMetaText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  carouselDots: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.md,
    flexDirection: 'row',
    gap: 6,
  },
  carouselDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
  },
  carouselDotActive: {
    width: 18,
    backgroundColor: '#FFFFFF',
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#172235',
    marginBottom: spacing.sm,
  },
  detailCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    padding: spacing.md,
    gap: spacing.smd,
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    shadowColor: colors.glassShadow,
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 14,
    elevation: 3,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.smd,
  },
  detailLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#667085',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#172235',
    textAlign: 'right',
    flexShrink: 1,
  },
  pricePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.full,
    backgroundColor: 'rgba(79, 70, 229, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(79, 70, 229, 0.24)',
  },
  pricePillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4338CA',
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.full,
    borderWidth: 1,
  },
  statusPillAvailable: {
    backgroundColor: 'rgba(16, 185, 129, 0.16)',
    borderColor: 'rgba(5, 150, 105, 0.26)',
  },
  statusPillOccupied: {
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: 'rgba(220, 38, 38, 0.22)',
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1F2937',
  },
  detailNote: {
    padding: spacing.smd,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
  },
  detailNoteText: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 20,
  },
  roommateList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  roommateItem: {
    width: '48%',
    minHeight: 62,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    backgroundColor: 'rgba(255, 255, 255, 0.62)',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  roommateAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#D8DEE8',
  },
  roommateFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5EAF2',
  },
  roommateName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#243247',
  },
  bottomCtaContainer: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
  },
  bottomCtaButton: {
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.glassBgStrong,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 5,
  },
  bottomCtaTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(124, 58, 237, 0.1)',
  },
  bottomCtaText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E2A3C',
  },
});

export default styles;
