// src/screens/EditProfileScreen.styles.ts
import { StyleSheet } from 'react-native';
import { makeSliderStyles } from '../styles/common';
import { Theme } from '../theme';

export const makeStyles = (theme: Theme) => ({
  ...makeSliderStyles(theme),
  ...StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.systemBackground,
    },
    header: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 24,
      paddingVertical: 16,
      backgroundColor: theme.colors.glassPanel,
    },
    headerActions: {
      flexDirection: 'row' as const,
      gap: 8,
    },
    content: {
      flex: 1,
      padding: 20,
    },
    sectionBlock: {
      marginBottom: 18,
    },
    sectionTitleMuted: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.colors.textSecondary,
      textTransform: 'uppercase' as const,
      letterSpacing: 0.6,
      marginBottom: 10,
    },
    sectionCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBackground,
      padding: 16,
      gap: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    photoGrid: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 10,
    },
    photoTile: {
      width: '31%' as const,
      aspectRatio: 1,
      borderRadius: 12,
      overflow: 'hidden' as const,
      backgroundColor: theme.colors.systemBackground,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    photo: {
      width: '100%' as const,
      height: '100%' as const,
    },
    photoPressArea: {
      width: '100%' as const,
      height: '100%' as const,
    },
    deleteButton: {
      position: 'absolute' as const,
      top: 6,
      right: 6,
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: 'rgba(239, 68, 68, 0.9)',
    },
    deleteButtonText: {
      fontSize: 12,
      fontWeight: '700' as const,
      color: '#FFFFFF',
    },
    primaryBadge: {
      position: 'absolute' as const,
      bottom: 6,
      left: 6,
      right: 6,
      paddingVertical: 4,
      backgroundColor: 'rgba(17, 24, 39, 0.85)',
      borderRadius: 8,
    },
    primaryBadgeText: {
      fontSize: 10,
      fontWeight: '600' as const,
      color: '#FFFFFF',
      textAlign: 'center' as const,
    },
    photoHint: {
      marginTop: 10,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    photoUploadingText: {
      marginTop: 8,
      fontSize: 12,
      color: theme.colors.text,
      fontWeight: '600' as const,
    },
    profileHeader: {
      alignItems: 'center' as const,
      marginBottom: 20,
    },
    avatarShell: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: theme.colors.glassBackground,
      borderWidth: 2,
      borderColor: theme.colors.primary,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    avatarImage: {
      width: 86,
      height: 86,
      borderRadius: 43,
    },
    avatarPlaceholder: {
      width: 86,
      height: 86,
      borderRadius: 43,
      backgroundColor: theme.colors.systemBackground,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    avatarEdit: {
      position: 'absolute' as const,
      top: -6,
      right: -6,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.colors.glassBackground,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 2,
    },
    profileHint: {
      marginTop: 12,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    editPhotosButton: {
      marginTop: 12,
      alignSelf: 'stretch' as const,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: 8,
      paddingVertical: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBackground,
    },
    editPhotosText: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.colors.text,
    },
    // ── Dark mode toggle row ──────────────────────────────────
    themeRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      paddingVertical: 12,
    },
    themeRowLabel: {
      fontSize: 15,
      fontWeight: '500' as const,
      color: theme.colors.text,
    },
    themeRowSub: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    switchLabel: {
      fontSize: 14,
      fontWeight: '600' as const,
      color: theme.colors.text,
      marginBottom: 10,
    },
    inlineLabel: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: theme.colors.textSecondary,
      marginBottom: 10,
    },
    checkGrid: {
      flexDirection: 'row' as const,
      flexWrap: 'wrap' as const,
      gap: 10,
      marginBottom: 16,
    },
    checkItem: {
      width: '48%' as const,
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBackground,
    },
    checkItemActive: {
      borderColor: theme.colors.primary,
      backgroundColor: 'rgba(124, 58, 237, 0.06)',
    },
    checkBox: {
      width: 18,
      height: 18,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.colors.disabled,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: theme.colors.glassBackground,
    },
    checkBoxActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    checkLabel: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.colors.text,
      flex: 1,
    },
    checkLabelActive: {
      color: theme.colors.primary,
    },
    checkItemDisabled: {
      opacity: 0.38,
    },
    checkLabelDisabled: {
      color: theme.colors.textTertiary,
    },
    checkEmoji: {
      fontSize: 16,
    },
    inlineMeta: {
      fontSize: 11,
      color: theme.colors.textTertiary,
      marginTop: -6,
      marginBottom: 10,
    },
    switchRow: {
      flexDirection: 'row' as const,
      gap: 10,
      marginBottom: 16,
    },
    switchButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBackground,
      alignItems: 'center' as const,
    },
    switchButtonActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    switchButtonText: {
      fontSize: 13,
      fontWeight: '600' as const,
      color: theme.colors.textSecondary,
    },
    switchButtonTextActive: {
      color: '#FFFFFF',
    },
    budgetContainer: {
      marginTop: 8,
      marginBottom: 8,
    },
    situacionContainer: {
      marginBottom: 16,
    },
    label: {
      fontSize: 14,
      fontWeight: '600' as const,
      marginBottom: 8,
      color: theme.colors.text,
    },
    situacionButtons: {
      flexDirection: 'row' as const,
      gap: 12,
    },
    situacionButton: {
      flex: 1,
      padding: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.glassBorder,
      backgroundColor: theme.colors.glassBackground,
    },
    situacionButtonActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    situacionButtonText: {
      textAlign: 'center' as const,
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    situacionButtonTextActive: {
      color: '#FFFFFF',
      fontWeight: '600' as const,
    },
  }),
});
