import { theme } from '../../theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F4F5F7',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.lg,
        paddingVertical: theme.spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        backgroundColor: theme.colors.background,
    },
    headerSpacer: {
        width: 48,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    headerIconButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.surfaceLight,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    headerIconDanger: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
    },
    actionButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
    },
    rejectButton: {
        borderColor: 'rgba(239, 68, 68, 0.25)',
    },
    likeButton: {
        borderColor: 'rgba(17, 24, 39, 0.2)',
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    tabsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 20,
    },
    tabButton: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: theme.borderRadius.full,
        borderWidth: 1,
        borderColor: theme.colors.border,
        alignItems: 'center',
        backgroundColor: theme.colors.background,
    },
    tabButtonActive: {
        borderColor: theme.colors.primary,
        backgroundColor: '#F5F3FF',
    },
    tabText: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    tabTextActive: {
        color: theme.colors.primary,
    },
    identityCard: {
        alignItems: 'center',
        marginBottom: 28,
        paddingVertical: 18,
        paddingHorizontal: 18,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
        shadowColor: theme.colors.text,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 3,
    },
    avatarWrap: {
        width: 96,
        height: 96,
        borderRadius: 48,
        overflow: 'hidden',
        backgroundColor: theme.colors.surfaceLight,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    avatarPlaceholder: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    identityName: {
        fontSize: 22,
        fontWeight: '700',
        color: theme.colors.text,
    },
    identityBadges: {
        marginTop: 10,
        alignItems: 'center',
        gap: theme.spacing.sm,
    },
    identityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: theme.spacing.sm,
        paddingHorizontal: 14,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.borderRadius.full,
        backgroundColor: theme.colors.surfaceLight,
    },
    identityBadgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.text,
    },
    identityBadgeLight: {
        paddingHorizontal: 14,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.borderRadius.full,
        borderWidth: 1,
        borderColor: '#D8B4FE',
        backgroundColor: theme.colors.background,
    },
    identityBadgeLightText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.primary,
    },
    photoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    photoTile: {
        width: '31%',
        aspectRatio: 1,
        borderRadius: theme.borderRadius.lg,
        overflow: 'hidden',
        backgroundColor: theme.colors.surfaceLight,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    photoTileImage: {
        width: '100%',
        height: '100%',
    },
    section: {
        marginBottom: 28,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
    },
    sectionMutedTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginBottom: 12,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 12,
    },
    aboutText: {
        fontSize: 15,
        color: theme.colors.text,
        marginBottom: 12,
    },
    detailCard: {
        backgroundColor: theme.colors.background,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        padding: theme.spacing.md,
        shadowColor: theme.colors.text,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailRowSpacing: {
        marginTop: 16,
    },
    detailIcon: {
        width: 40,
        height: 40,
        borderRadius: theme.borderRadius.md,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    detailIconBlue: {
        backgroundColor: '#DBEAFE',
    },
    detailIconGreen: {
        backgroundColor: '#DCFCE7',
    },
    detailText: {
        flex: 1,
    },
    detailLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        letterSpacing: 0.6,
    },
    detailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    mutedText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
    },
    flatList: {
        gap: theme.spacing.md,
    },
    flatCard: {
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        padding: theme.spacing.md,
        backgroundColor: theme.colors.background,
    },
    flatTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.text,
    },
    flatMeta: {
        marginTop: 6,
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    flatSection: {
        marginTop: 16,
    },
    flatSectionTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 8,
    },
    listContainer: {
        gap: 6,
    },
    listItem: {
        fontSize: 12,
        color: theme.colors.text,
    },
    roomList: {
        gap: 10,
    },
    roomCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 12,
        borderRadius: theme.borderRadius.md,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
    },
    roomPhoto: {
        width: 64,
        height: 64,
        borderRadius: theme.borderRadius.md,
        backgroundColor: theme.colors.surfaceLight,
    },
    roomPhotoPlaceholder: {
        width: 64,
        height: 64,
        borderRadius: theme.borderRadius.md,
        backgroundColor: theme.colors.surfaceLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    roomInfo: {
        flex: 1,
    },
    roomTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
    },
    roomMeta: {
        marginTop: 4,
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    manageCard: {
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
        padding: theme.spacing.md,
    },
    manageInfo: {
        marginBottom: 12,
    },
    manageTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    manageSubtitle: {
        marginTop: 6,
        fontSize: 13,
        color: theme.colors.textSecondary,
    },
    manageButton: {
        alignSelf: 'flex-start',
        paddingHorizontal: 14,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.borderRadius.full,
        backgroundColor: theme.colors.primary,
    },
    manageButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.background,
    },
    chipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: theme.spacing.sm,
    },
    outlineChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: theme.spacing.sm,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#D8B4FE',
        backgroundColor: theme.colors.background,
    },
    outlineChipText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.primary,
    },
    compactChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    compactChip: {
        paddingHorizontal: 14,
        paddingVertical: theme.spacing.sm,
        borderRadius: theme.borderRadius.full,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
        flexShrink: 1,
    },
    compactChipText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.text,
        flexShrink: 1,
    },
    chipIcon: {
        marginRight: 6,
    },
    ctaButton: {
        marginBottom: 32,
        backgroundColor: theme.colors.primary,
        borderRadius: 18,
        paddingVertical: 14,
        alignItems: 'center',
    },
    ctaText: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.background,
    },
    bottomActions: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 20,
        paddingHorizontal: theme.spacing.lg,
        paddingBottom: 24,
        paddingTop: 8,
        backgroundColor: theme.colors.background,
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
    },
    bottomButton: {
        width: 58,
        height: 58,
        borderRadius: 29,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderColor: 'rgba(255, 255, 255, 0.5)',
        overflow: 'hidden',
        shadowColor: theme.colors.text,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 6,
    },
    glassTint: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 29,
    },
    rejectTint: {
        backgroundColor: 'rgba(239, 68, 68, 0.08)',
    },
    likeTint: {
        backgroundColor: 'rgba(124, 58, 237, 0.08)',
    },
    lightboxOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    lightboxBackdrop: {
        ...StyleSheet.absoluteFillObject,
    },
    lightboxContent: {
        width: '90%',
        height: '70%',
        borderRadius: 20,
        overflow: 'hidden',
    },
    lightboxImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
        backgroundColor: theme.colors.text,
    },
    lightboxClose: {
        position: 'absolute',
        top: 14,
        right: 14,
        zIndex: 2,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(17, 24, 39, 0.8)',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
