import { theme } from '../../theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F4F5F7',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: theme.spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        backgroundColor: theme.colors.background,
        paddingBottom: 16,
    },
    headerActions: {
        flexDirection: 'row',
        gap: theme.spacing.sm,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    sectionBlock: {
        marginBottom: 18,
    },
    sectionTitleMuted: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 10,
    },
    sectionCard: {
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
        padding: theme.spacing.md,
        gap: 12,
        shadowColor: theme.colors.text,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    photoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    photoTile: {
        width: '31%',
        aspectRatio: 1,
        borderRadius: theme.borderRadius.md,
        overflow: 'hidden',
        backgroundColor: theme.colors.surfaceLight,
        borderWidth: 1,
        borderColor: theme.colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    photo: {
        width: '100%',
        height: '100%',
    },
    photoPressArea: {
        width: '100%',
        height: '100%',
    },
    deleteButton: {
        position: 'absolute',
        top: 6,
        right: 6,
        width: 24,
        height: 24,
        borderRadius: theme.borderRadius.md,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(239, 68, 68, 0.9)',
    },
    deleteButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: theme.colors.background,
    },
    primaryBadge: {
        position: 'absolute',
        bottom: 6,
        left: 6,
        right: 6,
        paddingVertical: 4,
        backgroundColor: 'rgba(17, 24, 39, 0.85)',
        borderRadius: theme.borderRadius.sm,
    },
    primaryBadgeText: {
        fontSize: 10,
        fontWeight: '600',
        color: theme.colors.background,
        textAlign: 'center',
    },
    photoHint: {
        marginTop: 10,
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    photoUploadingText: {
        marginTop: 8,
        fontSize: 12,
        color: theme.colors.text,
        fontWeight: '600',
    },
    profileHeader: {
        alignItems: 'center',
        marginBottom: 20,
    },
    avatarShell: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: theme.colors.background,
        borderWidth: 2,
        borderColor: theme.colors.text,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarImage: {
        width: 86,
        height: 86,
        borderRadius: 43,
    },
    avatarPlaceholder: {
        width: 86,
        height: 86,
        borderRadius: 43,
        backgroundColor: theme.colors.surfaceLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarEdit: {
        position: 'absolute',
        top: -6,
        right: -6,
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: theme.colors.background,
        borderWidth: 1,
        borderColor: theme.colors.border,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.colors.text,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 2,
    },
    profileHint: {
        marginTop: 12,
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    editPhotosButton: {
        marginTop: 12,
        alignSelf: 'stretch',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: theme.spacing.sm,
        paddingVertical: 12,
        borderRadius: theme.borderRadius.full,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
    },
    editPhotosText: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
    },
    switchLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 10,
    },
    inlineLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginBottom: 10,
    },
    checkGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 16,
    },
    checkItem: {
        width: '48%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
    },
    checkItemActive: {
        borderColor: theme.colors.text,
    },
    checkBox: {
        width: 18,
        height: 18,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: theme.colors.text,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.background,
    },
    checkBoxActive: {
        backgroundColor: theme.colors.text,
    },
    checkLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
    },
    checkLabelActive: {
        color: theme.colors.text,
    },
    switchRow: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 16,
    },
    switchButton: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: theme.borderRadius.full,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.surfaceLight,
        alignItems: 'center',
    },
    switchButtonActive: {
        backgroundColor: theme.colors.text,
        borderColor: theme.colors.text,
    },
    switchButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
    },
    switchButtonTextActive: {
        color: theme.colors.background,
    },
    budgetContainer: {
        marginTop: 8,
        marginBottom: 8,
    },
    budgetValues: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    budgetValue: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
    },
    situacionContainer: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
        color: theme.colors.text,
    },
    situacionButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    situacionButton: {
        flex: 1,
        padding: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.background,
    },
    situacionButtonActive: {
        backgroundColor: theme.colors.text,
        borderColor: theme.colors.text,
    },
    situacionButtonText: {
        textAlign: 'center',
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    situacionButtonTextActive: {
        color: theme.colors.background,
        fontWeight: '600',
    },
    sliderTrack: {
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.border,
    },
    sliderTrackActive: {
        position: 'absolute',
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.text,
    },
    sliderThumb: {
        position: 'absolute',
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: theme.colors.text,
        borderWidth: 2,
        borderColor: theme.colors.background,
        top: -7,
    },
    sliderTicks: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    sliderTick: {
        width: 2,
        height: 6,
        backgroundColor: theme.colors.disabled,
    },
    sliderLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 6,
    },
    sliderLabel: {
        fontSize: 11,
        color: theme.colors.textSecondary,
    },
});
